---
title: "Bases Científicas del ser Humano II - Fisiología"
subtitle: "Universidad de Magallanes - Terapia Ocupacional"
---

## Bienvenidos

Queridos estudiantes, bienvenidos. Este espacio es donde podrán encontrar material vinculado con el segmento de Fisiología de la asignatura *Bases Científicas del ser Humano II*, impartido para la carrera de Terapia Ocupacional de la Universidad de Magallanes para el año 2024.

## Fechas importantes

A continuación te dejo algunas fechas para que te mantengas organizado/a respecto de las próximas evaluaciones:

:::{.panel-tabset}
### Teoría

-  04/Diciembre: **Prueba Nº3 de Anatomofisiología**. Fisiología y Anatomía del sistema endocrino, renal y reproductor.

### Laboratorio

-  11/Noviembre: **Control del sistema endocrino**. Fisiología y Anatomía del sistema endocrino. Nota acumulativa.
-  25/Noviembre: **Control de anatomofisiología renal**. Fisiología y Anatomía del riñon. Nota acumulativa.
-  09/Diciembre: **Presentación de temas**. Asignación de temas en fisiología humana. Nota acumulativa.
:::

::: {.callout-note}
## Sobre este sitio

En este sitio encontrarán desde las clases (a medida que se vayan haciendo) hasta guías y material complementario que les ayudará a seguir aprendiendo.

<a class="btn btn-outline-primary" href="about.html">Ver más</a>
:::

## Enlaces directos

Para ver las clases subidas hasta el momento, pincha [aquí](clases.html), para revisar el material de apoyo disponible, pincha [acá](material.html)

## Profe, tengo una duda!

Si tienes dudas respecto a algo relacionado con la asignatura (horarios, material, etc) no dudes en escribirme a mi correo: [matias.castillo\@umag.cl](mailto:matias.castillo@umag.cl) o a Juan Carlos Carilao a [jcarilao\@umag.cl](mailto:jcarilao@umag.cl).
