---
title: "Material de apoyo"
---

## Guias

- [Guía de laboratorio de fisiología neuronal](material/guia-de-laboratorio-de-fisiologia-neuronal.pdf)
- [Guía de laboratorio de fisiología neuromuscular parte 1](materialguia-de-laboratorio-de-fisiologia-neuromuscular-parte-I.pdff)
- [Guía de laboratorio de fisiología neuromuscular parte 2](material/guia-de-laboratorio-de-fisiologia-neuromuscular-parte-II.pdf)
- [Guía de laboratorio de fisiología cardiovascular](material/guia-de-laboratorio-de-fisiologia-cardiovacular.pdf)
- [Guía de laboratorio de fisiología respiratoria](material/guia-de-laboratorio-de-fisiologia-respiratoria.pdf)
- [Guía de laboratorio de fisiología digestiva](material/guia-de-laboratorio-de-fisiologia-digestiva.pdf)
- [Guía de estudio de fisiología digestiva](material/guia-de-estudio-de-fisiologia-digestiva.pdf)
- [Guía de laboratorio de fisiología endocrina](material/guia-de-laboratorio-de-endocrino.pdf)

## Cuestionarios

- [Temas y preguntas Fisiología Cardiovascular](material/temas-y-preguntas-fisiologia-cardiovascular.pdf)

## Sitios web

- Nada todavía
